### ISSUE TITLE
Implement a global chat pane for chat clients that have their own tabbed interfaces like Chatterino

### ISSUE THREAD

**Issue by azizLIGHT** [Globidev/twitch-player#16]
Some chat clients have tabbed interfaces and can show multiple chat channels within one instance of themselves. Chatterino is a good example of a chat client like that:
![image](https://user-images.githubusercontent.com/8013867/54224394-cd03ad00-44cf-11e9-825b-3bf1088d09f1.png)

I've only loaded 1 pane in that screenshot, but if I were to add multiple panes with/without a chat, you can see that a single global chat pane that stands to the side (left or right) would be ideal here rather than multiple loads.

![image](https://user-images.githubusercontent.com/8013867/54224706-7185ef00-44d0-11e9-9603-f6b3416f69f9.png)

Here's a more exaggerated view that I hope makes the point
![image](https://user-images.githubusercontent.com/8013867/54224984-143e6d80-44d1-11e9-8f22-f10e0dc0f864.png)

**Comment by azizLIGHT** [comment]
On second thought, it's probably better to remove the chat renderer in the preferences and open Chatterino externally in this situation like this:

![image](https://user-images.githubusercontent.com/8013867/54227689-de03ec80-44d6-11e9-8903-c505f22c9bd1.png)

It's worth noting that removing the chat renderer so that it doesn't load Chrome (and hog memory/CPU), or Chatterino for every pane, will result in error messages that say "Failed to start the chat process" for every pane

It's upto you if you want to close this issue!

**Comment by Globidev** [comment]
Thanks for opening this.
I will toy with the idea of having a single chat subwindow for multiple stream windows and report back
I'll also make it so you can properly disable the chat renderer, I can see the error being annoying

**Comment by Globidev** [comment]
I added a new option to disable spawning chat renderers automatically
![image](https://user-images.githubusercontent.com/2079561/54252125-f103d480-4549-11e9-87cf-242468231989.png)
You can also now add "chat only" panes in the `View` menu:
![image](https://user-images.githubusercontent.com/2079561/54252155-0d077600-454a-11e9-8a25-a3677d2658e7.png)
This should be enough to cover your use case:
![image](https://user-images.githubusercontent.com/2079561/54252327-a20a6f00-454a-11e9-871f-0e0f52579887.png)
I don't have chatterino but you get the idea :)

The updated build is deployed too, you should be able to update through the maintenance tool
cheers

**Comment by azizLIGHT** [comment]
Thank you that looks sweet as hell

**Comment by azizLIGHT** [comment]
Sorry to bug you again, but I'm not entirely sure how you got that chat pane to go all the way from top to bottom on the side there. When I add my chat pane using left/right options, they just get added to the left/right in relation to a specific video pane that's currently selected with dotted lines, in a specific row. 
Screenshot:
![image](https://user-images.githubusercontent.com/8013867/54337256-bca11e80-4604-11e9-9b00-0d8c285b6103.png)
Another screenshot:
![image](https://user-images.githubusercontent.com/8013867/54337313-e22e2800-4604-11e9-8f43-6a7dbdae0a46.png)

Is there some specific order you added the panes that let the chat pane being vertically touching top to bottom like in your screenshot? I tried many variations like adding the chat pane first, then adding my video panes, or trying to add the rows first, then the columns, then chat pane etc, but still can't get the chat pane to be vertically expanded like your screenshot

**Comment by Globidev** [comment]
by default, the layout stacks vertically, you can use `View > Rotate layout` to change that

**Comment by azizLIGHT** [comment]
This is embarrassing. I can't get the layout to appear how you did. I am stupid and ashamed to ask for a step by step for the panes you added to get there...

**Comment by Globidev** [comment]
Don't worry, I'm not the best at making UIs either so I understand it can be confusing.
On top of that, the add directions become messed up when the layout is rotated, I should actually try to fix that.
What I did to take the screenshot above was basically this:
![demo](https://user-images.githubusercontent.com/2079561/54456653-98a62000-475f-11e9-8dba-9f3ba5b9c125.gif)

**Comment by azizLIGHT** [comment]
This is amazing. I got it to work thanks to your gif and explanation there. I LOVE THIS! Thank you so much!
![image](https://user-images.githubusercontent.com/8013867/54480667-92688000-4801-11e9-9de2-00986d5651da.png)
2x2 grid with Chatterino working! 3x3 also works but too lazy to screenshot. When I get back to my main machine I'll post some screenshots with crazier grids now that I understand the rotation aspect

**Comment by camjac251** [comment]
What would chatterino need to support for Twitch Player to auto switch chat tabs on stream focus or zoom? I wanted to open an issue on the project to hopefully see if that and command line arguments to get implemented but not sure what it is called.

Also too, are you guys getting `The application wasn't terminated properly the last time it was executed.` when new streams are opened (if the new chat option is enabled) or if you close the window and open a new stream?

**Comment by camjac251** [comment]
Just noticed when trying what you did in the gif that it bugged out when I tried to load a chatterino window on the bottom a second time, since the first got the error. I made 2 extra windows to the right, then one down and 2 right, then added a chat window on the bottom and removed it. But adding it again ends up adding it below the one on the left and rotating ends up crashing chatterino.

Is it possible to allow an option for the stream zoom option to keep the chat window on the far right on zoom in?

**Comment by Globidev** [comment]
> What would chatterino need to support for Twitch Player to auto switch chat tabs on stream focus or zoom? 

I doubt that's going to be possible with the current design. The embedded window comes from a completely detached process. We can only really control how Chatterino is spawned, not interact with it afterwards.

> Also too, are you guys getting `The application wasn't terminated properly the last time it was executed.`

Is that an error message coming from Chatterino ? I *should* be trying to close it relatively gracefully using standard messages on Windows so that's a bit concerning.

> Is it possible to allow an option for the stream zoom option to keep the chat window on the far right on zoom in?

I'll have to rethink the layout in order to allow such flexibility, maybe in the future.


Overall, I guess I should try to test Chatterino a bit more. The current way of embedding chats is flexible but relatively brittle in terms of control over it. I'm not so surprised to see unexpected behaviors coming from those applications

**Comment by camjac251** [comment]
> Is that an error message coming from Chatterino ? I _should_ be trying to close it relatively gracefully using standard messages on Windows so that's a bit concerning.

Yeah, whenever the window is closed using the Remove Active Pane option or I believe if toggled using the buttons on the bottom menu to toggle chat.

**Comment by azizLIGHT** [comment]
I get the Chatterino error message as well but I just ignore it. 

For what it's worth, any channels/splits I open in Chatterino while loaded inside Twitch Player wont get remembered. They won't be remembered the next time I open Chatterino inside Twitch Player nor will they be remembered in a plain Chatterino instance. I workaround this by loading the tabs/channels/splits I want in plain Chatterino first, then exit Chatterino, and then load Twitch Player with the chat pane with Chatterino inside. This way the layout sticks. I don't make many changes in Chatterino, so this works for me, YMMV
