### ISSUE TITLE
Remember window position and size

### ISSUE THREAD

**Issue by azizLIGHT** [Globidev/twitch-player#18]
I use Twitch-Player not maximized and every time I start it, I have to resize the window to my needs. I don't usually leave Twitch-Player running, so I go through many exits and starts. Would be helpful if it can remember what size I had the window in, and where I put it, so I don't have to do this again and again. Any possibility of this?

Related issue would be remembering the individual stream panes positioning and sizes as well. That would also be nice to have!

**Comment by Globidev** [comment]
Deployed the main window geometry persitency feature.

Regarding the internal layout, I'll probably ignore it in favor of the possibility to define and save specific layouts, as part of a more global rework
