### ISSUE TITLE
Feature: Option to hide menu that not ALT, maybe F9?

### ISSUE THREAD

**Issue by krab** [Globidev/twitch-player#20]
Any chance we getting mode like maximized window, without borders and menu?  https://i.imgur.com/TZhdFkC.jpg

Or just option to hide titlebar with menu so we can resize window manually, probably will be better, like potplayer https://i.imgur.com/cDost6y.png you can enable it via https://i.imgur.com/vzCaRIw.png option.

Currently it possible via "borderless gaming" software, but everytime you press "alt+tab" alt triggers menu show/hide action and its annoying.

Also this kind of "twitch player" i was looking for. It doesn't follow new twitch feature called "reduce stream quality in in-active browser tab" which makes stream lag and stop sometimes.

**Comment by krab** [comment]
Just found that potplayer like mode (without borders) enables via F10. Menu still triggers by alt button and appears every time you alt+tab, but never hides until you press alt again.

**Comment by Globidev** [comment]
I'll see if I can make the menubar toggle configurable, I have to admit that <kbd>ALT</kbd> was a poor choice to hardcode

**Comment by Globidev** [comment]
Implemented and deployed in `0.9.23`
