### ISSUE TITLE
Streams won't play

### ISSUE THREAD

**Issue by azizLIGHT** [Globidev/twitch-player#22]
Updated from 0.9.22 to 0.9.23 and tried to play a stream but cannot. The stream info like streamer name, stream title, game, along with UI buttons flicker and [Kappa keeps spinning](https://i.imgur.com/AydQEPb.gifv)

**Comment by Globidev** [comment]
This was fixed earlier (a8ece11) in a response to twitch playlist format changes overnight. Update to 0.9.24 (twitchd `1.4.4` being the key)

**Comment by azizLIGHT** [comment]
Thanks, that must have been a recent update that wasn't there in the maintenance tool when I tried to update a few hours ago today
