### ISSUE TITLE
Streams not playing: spinning Kappa forever

### ISSUE THREAD

**Issue by azizLIGHT** [Globidev/twitch-player#31]
Using version 0.9.24, whenever I click a stream, Kappa just spins forever and stream doesn't load. I tried maintenance tool to update, but there is no update available. Is it working for you?

[gif](https://imgur.com/a/Lu6TM57)

**Comment by Globidev** [comment]
Twitch have been performing some changes to their API, see [this streamlink issue thread](https://github.com/streamlink/streamlink/issues/2680) for details
Until things change again, you can apply the OAuth trick they mention to Twitch Player:
 1. Retrieve your private OAuth token from their website [as explained in section 2. of this comment](https://github.com/streamlink/streamlink/issues/2680#issuecomment-552024753)
 2. Close any instance of Twitch Player running
 3. Open the Windows registry editor (`regedit`)
 4. Go to `HKEY_CURRENT_USER\Software\GlobiCorp\Twitch Player\oauth` and change the value of `access-token` to the token you retrieved in step 1.

At the moment of writing this, streams play fine using this workaround.
I'll wait a bit to see if things change on Twitch's side, and if they don't I might end up adding a way to input a custom token without going through `regedit`
That's the best I can do at the moment I fear

Tell me if you manage to fix the issue by following those steps, I will then pin this issue. 
Sorry for the inconvenience

**Comment by azizLIGHT** [comment]
@Globidev Thanks this worked for me! 

For others, simply put: replace the oauth token in the registry with your own twitch account's oauth token, as explained by Globidev above
