### ISSUE TITLE
Wrong latency numbers

### ISSUE THREAD

**Issue by azizLIGHT** [Globidev/twitch-player#32]
Latency shown as 15-16 seconds when actual latency is around 1-2 seconds. Verified by running twitch player side by side with same stream running in browser with video stats on. Perhaps the calculation needs to be updated. This is not that big a deal but thought you should know

**Comment by Globidev** [comment]
If the gap is that high, it's probably your windows clock that's a bit out of sync
Check https://time.is/ to be sure.
Going in the windows time settings and turning automatic time off and on again is usually enough to force a resync

**Comment by azizLIGHT** [comment]
Wow I didn't think of that. That did fix it! Now I'm down to 3-4 seconds, which I'm going to chalk upto my internet connection at the moment.
