### ISSUE TITLE
Show stream related information

### ISSUE THREAD

**Issue by Globidev** [Globidev/twitch-player#8]
It would be nice to be able to see stream related information like the stream title, current viewer count, current game, etc...
This would require integrating some bits of Twitch's API

**Comment by Globidev** [comment]
implemented in 1d8cebf27c994c2bd8f528af2fb199d1de56a3a4
This does not make use of twitch's unofficial pubsub for viewer count updates yet

**Comment by camjac251** [comment]
Would it be possible to see stream uptime?

**Comment by Globidev** [comment]
Pretty sure that information is part of their API. That should be feasible, I'll reopen the issue to add that

**Comment by Globidev** [comment]
stream uptimes are now visible on stream cards while browsing:
![image](https://user-images.githubusercontent.com/2079561/54730732-c5589e00-4b8a-11e9-80c0-98e7cd6aee93.png)
and also on stream overlays:
![image](https://user-images.githubusercontent.com/2079561/54730740-d4d7e700-4b8a-11e9-808b-c9f3867351f2.png)

**Comment by camjac251** [comment]
That was fast. Thank you very much. This is awesome.

Would it be possible to add a black outline to the time on thumbnails? On bright thumbnails, the text blends in and it's hard to see.

**Comment by Globidev** [comment]
Right,
I will try to do that as part of a global overhaul of the stream cards design
